### ISSUE TITLE
Question?

### ISSUE THREAD

**Issue by raviteja06** [tzanou/VisibilityPercentageLayout#2]
I saw the second screenshot. Are you doing vertical recyclerview with fragments inside the view?

**Comment by tzanou** [comment]
Hello , its a vertical recyclerview with scrollview inside.Fragments would work as well.I will upload the code for the demo app I just have to clean it up a bit first

**Comment by raviteja06** [comment]
Thanks for you reply. I was working on a piece of code where i can initiate a fragment inside Recyclerview. I tried but didn't succeed. I got following errors.
1. If i specify fragment with a tag. it says tag name needs to be unique.
2. If i use frame layout and replace fragment, I can able to use back stack and show in each on the view. But it only detects the first view, everything else is empty. 

Thanks for your help in advance. let me know if you need more info.

**Comment by tzanou** [comment]
This has nothing to do with the library ,you can create a question at stackoverflow ...

**Comment by raviteja06** [comment]
Ya true. But Just sharing my work on it. Sure will post the question on SOF. Thanks for you help.
