### ISSUE TITLE
Setting Item height and width in percentage programactically 

### ISSUE THREAD

**Issue by Sutirth** [tzanou/VisibilityPercentageLayout#3]
Can I set height and width percentage programactically ??

**Comment by tzanou** [comment]
you mean setting a view to be for ex 50% height visible and 50% width visible programmatically?

**Comment by Sutirth** [comment]
Yep thats right and say its contains a child View setting it to  70% for e.g

**Comment by tzanou** [comment]
you can't do it directly from the library but you can write a loop that scrolls programmatically using .scrollBy(int x, int y) method until your desired visibility is reached

**Comment by Sutirth** [comment]
can you give me an example using code of your sample app??

**Comment by tzanou** [comment]
Say that you want to scroll until your view is 50% height visible

```
ScrollView mScrollView;     //Scrollview-RecyclerView-ListView  that contains PercentVisibleLayout
PercentVisibleLayout mPrercentVisibleLayout;   //you wrap your view with PercentVisibleLayout in your xml 
private scrollBool=true;

public void main(){

mPrercentVisibleLayout.setOnVisibilityPercentChangedListener(new PercentVisibleLayout.OnVisibilityPercentChanged() {
 @Override
public void onVisibilityChange(int verticalClip, int horizontalClip, int percentageHeight, int percentageWidth) {

        if(percentageHeight==50){
            scrollBool=false;
        }

        });

while(scrollBool){

mScrollView.scrollBy(intX, intY); 
//the step and direction that you want to scroll depends on your application and what you want to do  
}

}

```

**Comment by Sutirth** [comment]
<com.tzanou.PercentVisibleLayout.PercentVisibleLayout
        android:layout_width="300dp"
        android:layout_height="300dp"
        android:layout_gravity="center"
        android:id="@+id/custom_layout">

```
    <TextView
        android:layout_gravity="center"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:id="@+id/percentage_text"/>

</com.tzanou.PercentVisibleLayout.PercentVisibleLayout>
```

for e,g I need to set textView width and height in percentage can this be done??

**Comment by tzanou** [comment]
set width and height of percentVisibleLayout to wrap_content and the visibility percentage you get from the listener will be the textview percentage.To set it programmatically see the code I wrote above
